---
- name: Chrony Installed
  yum: name=chrony state=installed

- name: Chrony configured
  template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: '0644'
  register: chronyconf

- name: Chrony running
  service:
    name: chronyd
    state: restarted
  when: chronydconf.changed
